version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
      nodejs: 10
    commands:
      - npm -g install serverless
      - apt-get install -y jq
  build:
    commands:
      - make build STAGE=qa