version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
      nodejs: 10
    commands:
      - npm -g install serverless
      - apt-get install -y jq
  pre_build:
    commands:
      - echo "CODEBUILD_WEBHOOK_TRIGGER - $CODEBUILD_WEBHOOK_TRIGGER"
  build:
    commands:
      - mkdir -p serverless-functions/build/python/lib/python3.6/site-packages
      - bash deploy.sh