service: mozdef-event-framework
#app: your-app-name
#tenant: your-tenant-name

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"
provider:
  name: aws
  runtime: python3.7
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-west-2'}
  endpointType: REGIONAL
  tracing:
    apiGateway: true
    lambda: true
  tags:
    Project: ${self:custom.cfg.project}
  stackName: ${self:custom.cfg.resource_name}-${self:provider.stage}
  apiName: ${self:custom.cfg.resource_name}-eventframework-${self:provider.stage}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - sqs:SendMessage
        - sqs:GetQueueAttributes
        - sqs:ListQueues
      Resource: arn:aws:sqs:*:*:${self:custom.cfg.resource_name}
    - Effect: Allow
      Action: 
        - ssm:GetParameter
        - ssm:GetParametersByPath
      Resource:
        - "arn:aws:ssm:#{AWS::Region}:#{AWS::AccountId}:parameter/${self:custom.cfg.ssmZoomToken}"
    - Effect: Allow
      Action: kms:Decrypt
      Resource:
        # Using default AWS SSM key in KMS here, we can change if we want at the expense of more complexity
        - "arn:aws:kms:#{AWS::Region}:#{AWS::AccountId}:key/alias/aws/ssm"
  # You can define service wide environment variables here
  environment:
    REGION: '#{AWS::Region}'
    # Adding resource queue URL as global environment variable
    # We could also store this in SSM
    SQS_URL:
      Ref: ResourceQueue

package:
  # This is to keep the package to be uploaded as small as possible in size
  exclude:
    - .venv/**
    - .virtualenv/**
    - .git/**
    - __pycache__/**
    - node_modules/**
    - ./Makefile
    - .vscode
    - tests/**
# include:
#   - include-me.py
#   - include-me-dir/**

functions:
  testAuthorizer: 
    handler: authorizer.test
  eventframework:
    handler: handler.lambda_handler
    description: Lambda for handling webhook requests
    events:
      - http:
          path: ${self:custom.cfg.api_path}
          method: ${self:custom.cfg.api_method}
          cors: true
          authorizer: ${self:custom.authorizer.test}
          # I had to comment this out so I can get the full event data
          # async: true

#    The following are a few example events you can configure
#    NOTE: Please make sure to change your handler code to work with those events
#    Check the event documentation for details
#    events:
#      - http:
#          path: users/create
#          method: get
#      - websocket: $connect
#      - s3: ${env:BUCKET}
#      - schedule: rate(10 minutes)
#      - sns: greeter-topic
#      - stream: arn:aws:dynamodb:region:XXXXXX:table/foo/stream/1970-01-01T00:00:00.000
#      - alexaSkill: amzn1.ask.skill.xx-xx-xx-xx
#      - alexaSmartHome: amzn1.ask.skill.xx-xx-xx-xx
#      - iot:
#          sql: "SELECT * FROM 'some_topic'"
#      - cloudwatchEvent:
#          event:
#            source:
#              - "aws.ec2"
#            detail-type:
#              - "EC2 Instance State-change Notification"
#            detail:
#              state:
#                - pending
#      - cloudwatchLog: '/aws/lambda/hello'
#      - cognitoUserPool:
#          pool: MyUserPool
#          trigger: PreSignUp
#      - alb:
#          listenerArn: arn:aws:elasticloadbalancing:us-east-1:XXXXXX:listener/app/my-load-balancer/50dc6c495c0c9188/
#          priority: 1
#          conditions:
#            host: example.com
#            path: /hello

resources:
  Resources:
    RestApi:
      Type: 'AWS::ApiGateway::RestApi'
      Properties:
        Name: ${self:custom.cfg.resource_name}-eventframework-${self:provider.stage}
    ResourceQueue:    
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:custom.cfg.resource_name}
        MessageRetentionPeriod: 1209600
        VisibilityTimeout: 60
        RedrivePolicy:
          deadLetterTargetArn:
            Fn::GetAtt:
            - DeadLetterQueue
            - Arn
          maxReceiveCount: 10
    DeadLetterQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:custom.cfg.resource_name}-dead-letter-queue
        MessageRetentionPeriod: 1209600

# We will eventually need all these plugins, so adding them here
plugins:
  - serverless-python-requirements
  - serverless-pseudo-parameters
  - serverless-prune-plugin

custom:
  authorizer:
    test:
      name: testAuthorizer
      # type: request
      type: token
      identitySource: method.request.header.Authorization
      identityValidationExpression: '.*'
  cfg:
    resource_name: ZoomConnect
    # These are not final values
    api_method: POST
    api_path: zoom
    ssmZoomToken: mozdef-event-framework/ZOOM_AUTH_TOKEN
    project: MozDef
  pythonRequirements:
    dockerizePip: true
  prune:
    automatic: true
    number: 5